version: '3'
services:
  user-fe-swp391:
    image: ynnub2804/user-fe-swp391
    ports:
      - "3000:3000"
    environment:
      - VITE_PORT=3000

  admin-fe-swp391:
    image: ynnub2804/admin-fe-swp391
    ports:
      - "3001:3001"
    environment:
      - VITE_PORT=3001

  be-swp391:
    image: phuctth/be-swp391:latest
    ports:
      - "8088:8088"
    depends_on:
      - db
    environment:
      SERVER_PORT: 8088
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
      MYSQL_PORT: 3306
      GOOGLE_ID: 
      GOOGLE_SECRET:
      FACEBOOK_ID:
      FACEBOOK_SECRET:
      EMAIL: "email"
      EMAIL_PASSWORD: "1234"



  db:
    image: mysql:latest
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: birdfarmshop
      MYSQL_USER: phuctth
      MYSQL_PASSWORD: 1234
      
