version: '3'
services:
  user-fe-swp391:
    image: ynnub2804/user-fe-swp391
    environment:
      - VITE_PORT=3000

  admin-fe-swp391:
    image: ynnub2804/admin-fe-swp391
    environment:
      - VITE_PORT=3001

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./reverse-proxies.conf:/etc/nginx/default.d/reverse-proxies.conf
    ports:
      - "80:80"
    depends_on:
      - user-fe-swp391
      - admin-fe-swp391