version: '3'
services:
  user-fe-swp391:
    image: ynnub2804/user-fe-swp391
    ports:
      - "3000:3000"
    environment:
      - VITE_PORT=3000

  admin-fe-swp391:
    image: ynnub2804/admin-fe-swp391
    ports:
      - "3001:3001"
    environment:
      - VITE_PORT=3001

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf 
    ports:
      - "3000:3000"
      - "3001:3001"
    depends_on:
      - user-fe-swp391
      - admin-fe-swp391